version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/kafka/producer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/airflow"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/spark"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "AbdulSohail018"
    assignees:
      - "AbdulSohail018"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"